export const FETCH_CUSTOMER_DETAIL = 'FETCH_CUSTOMER_DETAIL';
export const FETCH_CUSTOMER_DETAIL_SUCCESS = 'FETCH_CUSTOMER_DETAIL_SUCCESS';
export const FETCH_PRODUCT_DETAIL= 'FETCH_PRODUCT_DETAIL';
export const FETCH_EMPLOYEE_DETAIL_SUCCESS= 'FETCH_EMPLOYEE_DETAIL_SUCCESS';
export const PUT_DESTINATION_SUCCESS= 'PUT_DESTINATION_SUCCESS';
export const PUT_PEVIEW_SHIPPING_SUCCESS= 'PUT_PEVIEW_SHIPPING_SUCCESS';
export const PUT_PAYMENT_SHIPPING_SUCCESS='PUT_PAYMENT_SHIPPING_SUCCESS';

export interface Action{
  type: string;
  payload: any
}
